### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cyal1** [EngineerDanny/apk-downloader#6]
```bash
ubuntu@VM-0-3-ubuntu:~/apk-downloader$ python3 main.py com.imdb.mobile
Hello, Welcome to APK Downloader !!!
Getting download link...
Found app name, APK would be named: IMDb:Movies&TVShows
Traceback (most recent call last):
  File "/home/ubuntu/apk-downloader/main.py", line 199, in <module>
    main()
  File "/home/ubuntu/apk-downloader/main.py", line 165, in main
    token = re.findall("token','([^\']+)", last_script)[0]
IndexError: list index out of range
```

**Comment by giganticlab** [comment]
same problem
